Adds EnumInjector for enums
spiral/framework pull request #693
Opened 2022-05-19 15:35 UTC by butschster

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌
| New feature?  | ✔️

### Enum 
```php
use Spiral\Boot\EnvironmentInterface;
use Spiral\Boot\Injector\ProvideFrom;
use Spiral\Boot\Injector\InjectableEnumInterface;

#[ProvideFrom(method: 'detect')]
enum AppEnvironment: string implements InjectableEnumInterface
{
    case Production = 'prod';
    case Stage = 'stage';
    case Testing = 'testing';
    case Local = 'local';

    public function isProduction(): bool
    {
        return $this === self::Production;
    }

    public static function detect(EnvironmentInterface $environment): self
    {
        $value = $environment->get('APP_ENV');

        return \is_string($value)
            ? (self::tryFrom($value) ?? self::Local)
            : self::Local;
    }
}
```

### Using

Enum will be automatically resolved by the container with current environment

```php
$appEnv = $container->get(AppEnvironment::class);

dump($appEnv->isProduction());
```

2022-05-20 19:19 UTC, msmakouz approved these changes

2022-05-20 19:43 UTC, roxblnfk requested changes

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Environment/DebugMode.php
> +        return filter_var($environment->get('DEBUG'), FILTER_VALIDATE_BOOL) ? self::Enabled : self::Disabled;
```suggestion
        return \filter_var($environment->get('DEBUG'), \FILTER_VALIDATE_BOOL) ? self::Enabled : self::Disabled;
```

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Injector/EnumInjector.php
> +        if (!$attribute) {
```suggestion
        if ($attribute === null) {
```

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Injector/EnumInjector.php
> +use Spiral\Core\Exception\Container\ContainerException;
```suggestion
use Spiral\Core\Exception\Container\InjectionException;
```

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Injector/EnumInjector.php
> +            throw new ContainerException(
```suggestion
            throw new InjectionException(
```

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Injector/EnumInjector.php
> +            throw new ContainerException(
```suggestion
            throw new InjectionException(
```

2022-05-20 19:43 UTC, roxblnfk commented on src/Boot/src/Injector/EnumInjector.php
> +        );
Check here please that `$attribute->method` is valid `callable`
Or you can wrap these lines with a `try/catch` block

2022-05-23 14:31 UTC, butschster reviewed
Small fixes

2022-05-23 15:16 UTC, roxblnfk approved these changes

2022-05-23 15:24 UTC, merged