[WIP] PSR-14 Event dispatcher
spiral/framework pull request #769
Opened 2022-08-31 09:40 UTC by butschster

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ✔️
| New feature?  | ✔️

2022-09-02 14:28 UTC, roxblnfk requested changes

2022-09-02 14:28 UTC, roxblnfk commented on src/Boot/src/AbstractKernel.php
> +        Container $container = new Container()
```suggestion
        Container $container = new Container(),
```

2022-09-02 14:28 UTC, roxblnfk commented on src/Boot/src/AbstractKernel.php
> +            null;
```suggestion
        $eventDispatcher = $this->container->has(EventDispatcherInterface::class)
            ? $this->container->get(EventDispatcherInterface::class)
            : null;
```

2022-09-02 14:28 UTC, roxblnfk commented on src/Boot/src/AbstractKernel.php
> +                    function () use ($dispatcher, $eventDispatcher): mixed {
```suggestion
                    static function () use ($dispatcher, $eventDispatcher): mixed {
```

2022-09-02 14:28 UTC, roxblnfk commented on src/Framework/Bootloader/Http/RouterBootloader.php
> +        );
You can use FactoryInterface instead

2022-09-02 14:28 UTC, roxblnfk commented on src/Router/src/Event/RouteFound.php
> +    ) {
What about Request object here?

2022-09-05 07:45 UTC, msmakouz commented on src/Boot/src/AbstractKernel.php
> +        Container $container = new Container()
Done.

2022-09-05 12:00 UTC, msmakouz commented on src/Events/.travis.yml
> +language: php
Removed.

2022-09-05 12:00 UTC, msmakouz commented on src/Events/README.md
> +[![Codecov](https://codecov.io/gh/spiral/csrf/branch/master/graph/badge.svg)](https://codecov.io/gh/spiral/csrf/)
Fixed.

2022-09-06 10:49 UTC, butschster commented
- `Symfony\Component\Console\Application` has an ability to inject EventDispatcher via `Spiral\Console\Console`
- `Symfony\Component\Mailer\Mailer` has an ability to inject EventDispatcher via `Spiral\SendIt\Bootloader\MailerBootloader`

2022-09-08 19:01 UTC, roxblnfk requested changes

2022-09-08 19:20 UTC, roxblnfk requested changes
Please add descriptions for all events in `Spiral\Boot\Event`

2022-09-08 21:46 UTC, roxblnfk approved these changes

2022-09-08 21:46 UTC, merged