Create TokenStorageProvider to able manage token storages
spiral/framework pull request #826
Opened 2022-10-26 10:33 UTC by kastahov

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌ 
| New feature?  | ✔️ 
| Issues        | #... 
| Docs PR       | spiral/docs#... 

Example:
```PHP
// in RoutesBootloader.php
return [
    'api' => [
        new Autowire(
            AuthTransportWithStorageMiddleware::class,
            ['transportName' => 'header', 'defaultStorage' => 'session']
        ),
        // or
        AuthTransportWithStorageMiddleware::class // defaultStorage will be 'session'
    ],
];

// 
```

2022-10-26 15:02 UTC, butschster requested changes

2022-10-27 09:25 UTC, butschster approved these changes

2022-10-27 11:12 UTC, msmakouz commented
I'm not sure if we need a separate `AuthTransportWithStorageMiddleware`.

It might be worth updating `AuthTransportMiddleware`:
1) Extend the type `TokenStorageInterface $tokenStorage` to `TokenStorageInterface|string $tokenStorage`
2) Add an optional parameter `TokenStorageProviderInterface` to the constructor.
3) In the `AuthTransportMiddleware` code, check if a string is passed and `TokenStorageProviderInterface` is not null (if it is null and storage string - throw an exception) - get the required storage from storage by its string name.

In version 4.0, we could make TokenStorageProviderInterface a required parameter and we can remove checking and exception.

2022-10-27 11:13 UTC, msmakouz approved these changes

2022-11-02 08:17 UTC, merged