Router improvements
spiral/framework pull request #831
Opened 2022-11-14 15:52 UTC by msmakouz

| Q             | A
| ------------- | ---
| Bugfix?       | ✔️
| Breaks BC?    | ❌ 
| New feature?  | ✔️

### Route name prefix

Added the ability to add a `prefix` to the `name` of all routes in a **group**. All route names in the group will start with the specified prefix.

Via `Spiral\Router\GroupRegistry`:

```php
namespace App\Bootloader;

use Spiral\Bootloader\Http\RoutesBootloader as BaseRoutesBootloader;
use Spiral\Router\GroupRegistry;

final class RoutesBootloader extends BaseRoutesBootloader
{
    // ...
    
    protected function configureRouteGroups(GroupRegistry $groups): void
    {
        $groups->getGroup('api')->setNamePrefix('api.');
    }
    
    // ...
}

```

Then add a route:

```php
#[Route(route: '/', name: 'index', group: 'api')]
public function index(): string
{
    return $this->views->render('home.dark.php');
}
```
The route name will be **api.index**:

```bash
+-----------+--------+----------+----------------------------------+--------+
| Name:     | Verbs: | Pattern: | Target:                          | Group: |
+-----------+--------+----------+----------------------------------+--------+
| api.index | *      | /        | Controller\HomeController->index | api    |
+-----------+--------+----------+----------------------------------+--------+
```
Or via `Spiral\Router\Loader\Configurator\RoutingConfigurator` during import from a file:

```php
namespace App\Bootloader;

use Spiral\Bootloader\Http\RoutesBootloader as BaseRoutesBootloader;
use Spiral\Router\Loader\Configurator\RoutingConfigurator;

final class RoutesBootloader extends BaseRoutesBootloader
{
    // ...
    
    protected function defineRoutes(RoutingConfigurator $routes): void
    {
        $routes
            ->import(\dirname(__DIR__, 2) . '/routes/api.php')
            ->group('api')
            ->prefix('api')
            ->namePrefix('api.');
    }
    
    // ...
}
```

### Default group in the Annotated Routes

Added the ability to set a default group for routes added by the Annotated Routes package.

```php
namespace App\Bootloader;

use Spiral\Bootloader\Http\RoutesBootloader as BaseRoutesBootloader;
use Spiral\Router\GroupRegistry;

final class RoutesBootloader extends BaseRoutesBootloader
{
    // ...
    
    protected function configureRouteGroups(GroupRegistry $groups): void
    {
        $groups->setDefaultGroup('custom');
    }
    
    // ...
}
```

### Method **configureRouteGroups** in the **RoutesBootloader**

Added the ability to add the `configureRouteGroups` method to the `RoutesBootloader` class. The method will be called automatically and one `Spiral\Router\GroupRegistry` parameter will be passed to it. With this method, you can easilyconfigure route groups.

### Prefix

Fixed bug with the route prefix in groups.

2022-11-16 17:21 UTC, butschster requested changes

2022-11-16 17:21 UTC, butschster commented on src/Framework/Bootloader/Http/RouterBootloader.php
> +            $groups->registerRoutes();
Pass `$router` into `registerRoutes` method

2022-11-16 17:21 UTC, butschster commented on src/Router/src/GroupRegistry.php
> +    public function registerRoutes(): void
Pass router into method

2022-11-16 17:21 UTC, butschster commented on src/Router/src/RouteGroup.php
>  final class RouteGroup
Let's mark it as internal?

2022-11-16 19:46 UTC, msmakouz commented on src/Router/src/RouteGroup.php
> +        $this->bindMiddlewares();
This method has been removed.

2022-11-16 20:03 UTC, msmakouz commented on src/Router/src/GroupRegistry.php
> +    public function registerRoutes(): void
Done.

2022-11-16 20:04 UTC, msmakouz commented on src/Framework/Bootloader/Http/RouterBootloader.php
> +            $groups->registerRoutes();
Done.

2022-11-17 06:09 UTC, butschster approved these changes

2022-11-17 06:15 UTC, merged