Add route pattern registry
spiral/framework pull request #847
Opened 2022-12-13 12:44 UTC by kastahov

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌ 
| New feature?  | ✔️

2022-12-14 10:22 UTC, butschster requested changes

2022-12-14 14:22 UTC, msmakouz requested changes

2022-12-14 14:22 UTC, msmakouz commented on src/Router/src/Registry/DefaultPatternRegistry.php
> +    public function register(string $name, string|\Stringable $pattern): void
```suggestion
    /**
     * @param non-empty-string $name
     * @param non-empty-string|\Stringable $pattern
     */
    public function register(string $name, string|\Stringable $pattern): void
```

2022-12-14 14:22 UTC, msmakouz commented on src/Router/src/Registry/DefaultPatternRegistry.php
> +    public function all(): array
```suggestion
    /**
     * @return array<non-empty-string, non-empty-string>
     */
    public function all(): array
```

2022-12-14 14:22 UTC, msmakouz commented on src/Router/src/Registry/RoutePatternRegistryInterface.php
> +    public function register(string $name, string|\Stringable $pattern): void;
```suggestion
    /**
     * @param non-empty-string $name
     * @param non-empty-string|\Stringable $pattern
     */
    public function register(string $name, string|\Stringable $pattern): void;
```

2022-12-14 19:49 UTC, butschster requested changes

2022-12-14 19:49 UTC, butschster commented on src/Router/src/Registry/DefaultPatternRegistry.php
> +    /**
Phpdoc duplication

2022-12-14 19:49 UTC, butschster commented on src/Router/src/UriHandler.php
> +        private readonly ?RoutePatternRegistryInterface $patternRegistry = new DefaultPatternRegistry()
```suggestion
        private readonly ?RoutePatternRegistryInterface $patternRegistry = new DefaultPatternRegistry(),
```

2022-12-15 10:50 UTC, butschster approved these changes

2022-12-19 07:48 UTC, merged