Adding the ability to configure a prefix in the storage alias
spiral/framework pull request #869
Opened 2023-01-30 18:21 UTC by msmakouz

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌ 
| New feature?  | ✔️

2023-01-31 07:51 UTC, butschster requested changes

2023-01-31 07:51 UTC, butschster commented on src/Cache/src/CacheManager.php
> +        if (isset($this->storages[$storage])) {
```php
if(!isset($this->storages[$storage])) {
    $this->storages[$storage] = $this->resolve($storage);
}

return new CacheRepository($this->storages[$storage], $this->dispatcher, $prefix);
```

2023-01-31 15:45 UTC, msmakouz commented on src/Cache/src/CacheManager.php
> +        if (isset($this->storages[$storage])) {
Fixed, thanks

2023-02-01 10:43 UTC, butschster approved these changes

2023-02-01 10:44 UTC, merged