[spiral/tokenizer] Create Enum loader
spiral/framework pull request #947
Opened 2023-06-20 16:43 UTC by andrey-mokhov

| Q             | A
| ------------- | ---
| Bugfix?       | ❌
| Breaks BC?    | ❌
| New feature?  | ✔️
| Issues        | ❌

Allows you to load enums and interfaces for later analysis in listeners.

2023-07-03 08:44 UTC, butschster requested changes

2023-07-03 08:44 UTC, butschster commented on src/Tokenizer/src/Bootloader/TokenizerListenerBootloader.php
> +            if (call_user_func($loader, $listener)) {
```suggestion
            if (\call_user_func($loader, $listener)) {
```

2023-07-03 08:44 UTC, butschster commented on src/Tokenizer/src/Bootloader/TokenizerListenerBootloader.php
> +        $classes = call_user_func($reflections);
```suggestion
        $classes = \call_user_func($reflections);
```

2023-07-03 08:44 UTC, butschster commented on src/Tokenizer/src/Listener/CachedEnumsLoader.php
> +            static fn (string $enum) => new \ReflectionEnum($enum),
```suggestion
            static fn (string $enum): \ReflectionEnum => new \ReflectionEnum($enum),
```

2023-07-03 08:44 UTC, butschster commented on src/Tokenizer/src/Listener/CachedInterfacesLoader.php
> +            static fn (string $class) => new \ReflectionClass($class),
```suggestion
            static fn (string $class): \ReflectionClass => new \ReflectionClass($class),
```

2023-07-12 09:58 UTC, msmakouz approved these changes

2023-07-12 10:03 UTC, butschster commented
@andrey-mokhov Привет, ты уже тестировал, все ок?

2023-07-12 10:21 UTC, andrey-mokhov commented
@butschster да, моя либа работает с этими изменениями отлично

2023-07-12 11:18 UTC, merged